const io = require("socket.io-client");

const MONITORS = [
    {
        name: "Production API",
        type: "http",
        url: "https://example.com",
        interval: 60,
        retryInterval: 60,
        maxretries: 1,
        upsideDown: false,
        notificationIDList: {},
        ignoreTls: false,
        expiryNotification: false,
        maxredirects: 10,
        accepted_statuscodes: ["200-299"],
        proxyId: null,
        method: "GET",
        body: "",
        headers: "",
        authMethod: "",
        hostname: null,
        port: null,
        dns_resolve_server: "1.1.1.1",
        dns_resolve_type: "A",
        packetSize: 56,
        mqttUsername: "",
        mqttPassword: "",
        mqttTopic: "",
        mqttSuccessMessage: "",
        databaseConnectionString: "",
        databaseQuery: "",
        radiusSecret: "",
        radiusCalledStationId: "",
        radiusCallingStationId: "",
        game: null,
        gamedigGivenPortOnly: true,
        httpBodyEncoding: "follow",
        jsonPath: "",
        expectedValue: "",
        kafkaProducerBrokers: [],
        kafkaProducerTopic: "",
        kafkaProducerMessage: "",
        kafkaProducerSaslOptions: { mechanism: "None" },
        tlsCa: "",
        tlsCert: "",
        tlsKey: "",
        basic_auth_user: "",
        basic_auth_pass: "",
        oauth_auth_method: "client_secret_basic",
        oauth_token_url: "",
        oauth_client_id: "",
        oauth_client_secret: "",
        oauth_scopes: "",
        timeout: 0,
        cache_bust: false,
        conditions: [],
        rabbitmq_nodes: [],
        screenshot_delay: 0,
        save_response: false,
        save_error_response: true,
        response_max_length: 1024,
        retry_only_on_status_code_failure: false,
    },
    {
        name: "Checkout Service",
        type: "http",
        url: "https://httpstat.us/200",
        interval: 60,
        retryInterval: 60,
        maxretries: 1,
        upsideDown: false,
        notificationIDList: {},
        ignoreTls: false,
        expiryNotification: false,
        maxredirects: 10,
        accepted_statuscodes: ["200-299"],
        proxyId: null,
        method: "GET",
        body: "",
        headers: "",
        authMethod: "",
        hostname: null,
        port: null,
        dns_resolve_server: "1.1.1.1",
        dns_resolve_type: "A",
        packetSize: 56,
        mqttUsername: "",
        mqttPassword: "",
        mqttTopic: "",
        mqttSuccessMessage: "",
        databaseConnectionString: "",
        databaseQuery: "",
        radiusSecret: "",
        radiusCalledStationId: "",
        radiusCallingStationId: "",
        game: null,
        gamedigGivenPortOnly: true,
        httpBodyEncoding: "follow",
        jsonPath: "",
        expectedValue: "",
        kafkaProducerBrokers: [],
        kafkaProducerTopic: "",
        kafkaProducerMessage: "",
        kafkaProducerSaslOptions: { mechanism: "None" },
        tlsCa: "",
        tlsCert: "",
        tlsKey: "",
        basic_auth_user: "",
        basic_auth_pass: "",
        oauth_auth_method: "client_secret_basic",
        oauth_token_url: "",
        oauth_client_id: "",
        oauth_client_secret: "",
        oauth_scopes: "",
        timeout: 0,
        cache_bust: false,
        conditions: [],
        rabbitmq_nodes: [],
        screenshot_delay: 0,
        save_response: false,
        save_error_response: true,
        response_max_length: 1024,
        retry_only_on_status_code_failure: false,
    },
    {
        name: "Auth Service",
        type: "http",
        url: "http://localhost:19999",
        interval: 60,
        retryInterval: 60,
        maxretries: 1,
        upsideDown: false,
        notificationIDList: {},
        ignoreTls: false,
        expiryNotification: false,
        maxredirects: 10,
        accepted_statuscodes: ["200-299"],
        proxyId: null,
        method: "GET",
        body: "",
        headers: "",
        authMethod: "",
        hostname: null,
        port: null,
        dns_resolve_server: "1.1.1.1",
        dns_resolve_type: "A",
        packetSize: 56,
        mqttUsername: "",
        mqttPassword: "",
        mqttTopic: "",
        mqttSuccessMessage: "",
        databaseConnectionString: "",
        databaseQuery: "",
        radiusSecret: "",
        radiusCalledStationId: "",
        radiusCallingStationId: "",
        game: null,
        gamedigGivenPortOnly: true,
        httpBodyEncoding: "follow",
        jsonPath: "",
        expectedValue: "",
        kafkaProducerBrokers: [],
        kafkaProducerTopic: "",
        kafkaProducerMessage: "",
        kafkaProducerSaslOptions: { mechanism: "None" },
        tlsCa: "",
        tlsCert: "",
        tlsKey: "",
        basic_auth_user: "",
        basic_auth_pass: "",
        oauth_auth_method: "client_secret_basic",
        oauth_token_url: "",
        oauth_client_id: "",
        oauth_client_secret: "",
        oauth_scopes: "",
        timeout: 0,
        cache_bust: false,
        conditions: [],
        rabbitmq_nodes: [],
        screenshot_delay: 0,
        save_response: false,
        save_error_response: true,
        response_max_length: 1024,
        retry_only_on_status_code_failure: false,
    },
    {
        name: "Database Primary",
        type: "ping",
        url: "127.0.0.1",
        interval: 60,
        retryInterval: 60,
        maxretries: 1,
        upsideDown: false,
        notificationIDList: {},
        ignoreTls: false,
        expiryNotification: false,
        maxredirects: 10,
        accepted_statuscodes: ["200-299"],
        proxyId: null,
        method: "GET",
        body: "",
        headers: "",
        authMethod: "",
        hostname: null,
        port: null,
        dns_resolve_server: "1.1.1.1",
        dns_resolve_type: "A",
        packetSize: 56,
        mqttUsername: "",
        mqttPassword: "",
        mqttTopic: "",
        mqttSuccessMessage: "",
        databaseConnectionString: "",
        databaseQuery: "",
        radiusSecret: "",
        radiusCalledStationId: "",
        radiusCallingStationId: "",
        game: null,
        gamedigGivenPortOnly: true,
        httpBodyEncoding: "follow",
        jsonPath: "",
        expectedValue: "",
        kafkaProducerBrokers: [],
        kafkaProducerTopic: "",
        kafkaProducerMessage: "",
        kafkaProducerSaslOptions: { mechanism: "None" },
        tlsCa: "",
        tlsCert: "",
        tlsKey: "",
        basic_auth_user: "",
        basic_auth_pass: "",
        oauth_auth_method: "client_secret_basic",
        oauth_token_url: "",
        oauth_client_id: "",
        oauth_client_secret: "",
        oauth_scopes: "",
        timeout: 0,
        cache_bust: false,
        conditions: [],
        rabbitmq_nodes: [],
        screenshot_delay: 0,
        save_response: false,
        save_error_response: true,
        response_max_length: 1024,
        retry_only_on_status_code_failure: false,
    },
    {
        name: "CDN Edge Node",
        type: "http",
        url: "https://httpstat.us/503",
        interval: 60,
        retryInterval: 60,
        maxretries: 1,
        upsideDown: false,
        notificationIDList: {},
        ignoreTls: false,
        expiryNotification: false,
        maxredirects: 10,
        accepted_statuscodes: ["200-299"],
        proxyId: null,
        method: "GET",
        body: "",
        headers: "",
        authMethod: "",
        hostname: null,
        port: null,
        dns_resolve_server: "1.1.1.1",
        dns_resolve_type: "A",
        packetSize: 56,
        mqttUsername: "",
        mqttPassword: "",
        mqttTopic: "",
        mqttSuccessMessage: "",
        databaseConnectionString: "",
        databaseQuery: "",
        radiusSecret: "",
        radiusCalledStationId: "",
        radiusCallingStationId: "",
        game: null,
        gamedigGivenPortOnly: true,
        httpBodyEncoding: "follow",
        jsonPath: "",
        expectedValue: "",
        kafkaProducerBrokers: [],
        kafkaProducerTopic: "",
        kafkaProducerMessage: "",
        kafkaProducerSaslOptions: { mechanism: "None" },
        tlsCa: "",
        tlsCert: "",
        tlsKey: "",
        basic_auth_user: "",
        basic_auth_pass: "",
        oauth_auth_method: "client_secret_basic",
        oauth_token_url: "",
        oauth_client_id: "",
        oauth_client_secret: "",
        oauth_scopes: "",
        timeout: 0,
        cache_bust: false,
        conditions: [],
        rabbitmq_nodes: [],
        screenshot_delay: 0,
        save_response: false,
        save_error_response: true,
        response_max_length: 1024,
        retry_only_on_status_code_failure: false,
    },
    {
        name: "Webhook Receiver",
        type: "http",
        url: "http://localhost:19998",
        interval: 60,
        retryInterval: 60,
        maxretries: 1,
        upsideDown: false,
        notificationIDList: {},
        ignoreTls: false,
        expiryNotification: false,
        maxredirects: 10,
        accepted_statuscodes: ["200-299"],
        proxyId: null,
        method: "GET",
        body: "",
        headers: "",
        authMethod: "",
        hostname: null,
        port: null,
        dns_resolve_server: "1.1.1.1",
        dns_resolve_type: "A",
        packetSize: 56,
        mqttUsername: "",
        mqttPassword: "",
        mqttTopic: "",
        mqttSuccessMessage: "",
        databaseConnectionString: "",
        databaseQuery: "",
        radiusSecret: "",
        radiusCalledStationId: "",
        radiusCallingStationId: "",
        game: null,
        gamedigGivenPortOnly: true,
        httpBodyEncoding: "follow",
        jsonPath: "",
        expectedValue: "",
        kafkaProducerBrokers: [],
        kafkaProducerTopic: "",
        kafkaProducerMessage: "",
        kafkaProducerSaslOptions: { mechanism: "None" },
        tlsCa: "",
        tlsCert: "",
        tlsKey: "",
        basic_auth_user: "",
        basic_auth_pass: "",
        oauth_auth_method: "client_secret_basic",
        oauth_token_url: "",
        oauth_client_id: "",
        oauth_client_secret: "",
        oauth_scopes: "",
        timeout: 0,
        cache_bust: false,
        conditions: [],
        rabbitmq_nodes: [],
        screenshot_delay: 0,
        save_response: false,
        save_error_response: true,
        response_max_length: 1024,
        retry_only_on_status_code_failure: false,
    },
    {
        name: "Internal DNS",
        type: "ping",
        url: "1.1.1.1",
        interval: 60,
        retryInterval: 60,
        maxretries: 1,
        upsideDown: false,
        notificationIDList: {},
        ignoreTls: false,
        expiryNotification: false,
        maxredirects: 10,
        accepted_statuscodes: ["200-299"],
        proxyId: null,
        method: "GET",
        body: "",
        headers: "",
        authMethod: "",
        hostname: null,
        port: null,
        dns_resolve_server: "1.1.1.1",
        dns_resolve_type: "A",
        packetSize: 56,
        mqttUsername: "",
        mqttPassword: "",
        mqttTopic: "",
        mqttSuccessMessage: "",
        databaseConnectionString: "",
        databaseQuery: "",
        radiusSecret: "",
        radiusCalledStationId: "",
        radiusCallingStationId: "",
        game: null,
        gamedigGivenPortOnly: true,
        httpBodyEncoding: "follow",
        jsonPath: "",
        expectedValue: "",
        kafkaProducerBrokers: [],
        kafkaProducerTopic: "",
        kafkaProducerMessage: "",
        kafkaProducerSaslOptions: { mechanism: "None" },
        tlsCa: "",
        tlsCert: "",
        tlsKey: "",
        basic_auth_user: "",
        basic_auth_pass: "",
        oauth_auth_method: "client_secret_basic",
        oauth_token_url: "",
        oauth_client_id: "",
        oauth_client_secret: "",
        oauth_scopes: "",
        timeout: 0,
        cache_bust: false,
        conditions: [],
        rabbitmq_nodes: [],
        screenshot_delay: 0,
        save_response: false,
        save_error_response: true,
        response_max_length: 1024,
        retry_only_on_status_code_failure: false,
    },
    {
        name: "Backup Server",
        type: "ping",
        url: "8.8.8.8",
        interval: 60,
        retryInterval: 60,
        maxretries: 1,
        upsideDown: false,
        notificationIDList: {},
        ignoreTls: false,
        expiryNotification: false,
        maxredirects: 10,
        accepted_statuscodes: ["200-299"],
        proxyId: null,
        method: "GET",
        body: "",
        headers: "",
        authMethod: "",
        hostname: null,
        port: null,
        dns_resolve_server: "1.1.1.1",
        dns_resolve_type: "A",
        packetSize: 56,
        mqttUsername: "",
        mqttPassword: "",
        mqttTopic: "",
        mqttSuccessMessage: "",
        databaseConnectionString: "",
        databaseQuery: "",
        radiusSecret: "",
        radiusCalledStationId: "",
        radiusCallingStationId: "",
        game: null,
        gamedigGivenPortOnly: true,
        httpBodyEncoding: "follow",
        jsonPath: "",
        expectedValue: "",
        kafkaProducerBrokers: [],
        kafkaProducerTopic: "",
        kafkaProducerMessage: "",
        kafkaProducerSaslOptions: { mechanism: "None" },
        tlsCa: "",
        tlsCert: "",
        tlsKey: "",
        basic_auth_user: "",
        basic_auth_pass: "",
        oauth_auth_method: "client_secret_basic",
        oauth_token_url: "",
        oauth_client_id: "",
        oauth_client_secret: "",
        oauth_scopes: "",
        timeout: 0,
        cache_bust: false,
        conditions: [],
        rabbitmq_nodes: [],
        screenshot_delay: 0,
        save_response: false,
        save_error_response: true,
        response_max_length: 1024,
        retry_only_on_status_code_failure: false,
    },
    {
        name: "Staging API",
        type: "http",
        url: "https://httpstat.us/301",
        interval: 60,
        retryInterval: 60,
        maxretries: 1,
        upsideDown: false,
        notificationIDList: {},
        ignoreTls: false,
        expiryNotification: false,
        maxredirects: 10,
        accepted_statuscodes: ["200-299"],
        proxyId: null,
        method: "GET",
        body: "",
        headers: "",
        authMethod: "",
        hostname: null,
        port: null,
        dns_resolve_server: "1.1.1.1",
        dns_resolve_type: "A",
        packetSize: 56,
        mqttUsername: "",
        mqttPassword: "",
        mqttTopic: "",
        mqttSuccessMessage: "",
        databaseConnectionString: "",
        databaseQuery: "",
        radiusSecret: "",
        radiusCalledStationId: "",
        radiusCallingStationId: "",
        game: null,
        gamedigGivenPortOnly: true,
        httpBodyEncoding: "follow",
        jsonPath: "",
        expectedValue: "",
        kafkaProducerBrokers: [],
        kafkaProducerTopic: "",
        kafkaProducerMessage: "",
        kafkaProducerSaslOptions: { mechanism: "None" },
        tlsCa: "",
        tlsCert: "",
        tlsKey: "",
        basic_auth_user: "",
        basic_auth_pass: "",
        oauth_auth_method: "client_secret_basic",
        oauth_token_url: "",
        oauth_client_id: "",
        oauth_client_secret: "",
        oauth_scopes: "",
        timeout: 0,
        cache_bust: false,
        conditions: [],
        rabbitmq_nodes: [],
        screenshot_delay: 0,
        save_response: false,
        save_error_response: true,
        response_max_length: 1024,
        retry_only_on_status_code_failure: false,
    },
    {
        name: "Legacy Portal",
        type: "http",
        url: "https://httpstat.us/404",
        interval: 60,
        retryInterval: 60,
        maxretries: 1,
        upsideDown: false,
        notificationIDList: {},
        ignoreTls: false,
        expiryNotification: false,
        maxredirects: 10,
        accepted_statuscodes: ["200-299"],
        proxyId: null,
        method: "GET",
        body: "",
        headers: "",
        authMethod: "",
        hostname: null,
        port: null,
        dns_resolve_server: "1.1.1.1",
        dns_resolve_type: "A",
        packetSize: 56,
        mqttUsername: "",
        mqttPassword: "",
        mqttTopic: "",
        mqttSuccessMessage: "",
        databaseConnectionString: "",
        databaseQuery: "",
        radiusSecret: "",
        radiusCalledStationId: "",
        radiusCallingStationId: "",
        game: null,
        gamedigGivenPortOnly: true,
        httpBodyEncoding: "follow",
        jsonPath: "",
        expectedValue: "",
        kafkaProducerBrokers: [],
        kafkaProducerTopic: "",
        kafkaProducerMessage: "",
        kafkaProducerSaslOptions: { mechanism: "None" },
        tlsCa: "",
        tlsCert: "",
        tlsKey: "",
        basic_auth_user: "",
        basic_auth_pass: "",
        oauth_auth_method: "client_secret_basic",
        oauth_token_url: "",
        oauth_client_id: "",
        oauth_client_secret: "",
        oauth_scopes: "",
        timeout: 0,
        cache_bust: false,
        conditions: [],
        rabbitmq_nodes: [],
        screenshot_delay: 0,
        save_response: false,
        save_error_response: true,
        response_max_length: 1024,
        retry_only_on_status_code_failure: false,
    },
];

const PAUSED_MONITOR_NAMES = ["Webhook Receiver", "Backup Server"];

async function seed() {
    const socket = io("http://localhost:3001");

    await new Promise((resolve, reject) => {
        socket.on("connect", resolve);
        socket.on("connect_error", reject);
        setTimeout(() => reject(new Error("Connection timeout")), 10000);
    });

    console.log("Connected to Uptime Kuma");

    // Login
    const loginRes = await new Promise((resolve) => {
        socket.emit("login", { username: "admin", password: "admin12345" }, resolve);
    });

    if (!loginRes.ok) {
        throw new Error("Login failed: " + JSON.stringify(loginRes));
    }
    console.log("Logged in successfully");

    // Create monitors
    const monitorIds = {};
    for (const monitor of MONITORS) {
        const addRes = await new Promise((resolve) => {
            socket.emit("add", monitor, resolve);
        });

        if (!addRes.ok) {
            throw new Error(`Failed to add monitor '${monitor.name}': ${addRes.msg}`);
        }

        monitorIds[monitor.name] = addRes.monitorID;
        console.log(`Created monitor: ${monitor.name} (ID: ${addRes.monitorID})`);
    }

    // Pause selected monitors
    for (const name of PAUSED_MONITOR_NAMES) {
        const id = monitorIds[name];
        if (id) {
            const pauseRes = await new Promise((resolve) => {
                socket.emit("pauseMonitor", id, resolve);
            });

            if (!pauseRes.ok) {
                throw new Error(`Failed to pause monitor '${name}': ${pauseRes.msg}`);
            }
            console.log(`Paused monitor: ${name}`);
        }
    }

    // Create a status page
    const addStatusPageRes = await new Promise((resolve) => {
        socket.emit("addStatusPage", "Platform Status", "platform", resolve);
    });

    if (!addStatusPageRes.ok) {
        throw new Error("Failed to add status page: " + addStatusPageRes.msg);
    }
    console.log("Created status page: Platform Status");

    // Configure the status page with monitors
    const allMonitorIds = Object.values(monitorIds);
    const publicGroupList = [
        {
            name: "Core Services",
            weight: 1,
            monitorList: allMonitorIds.slice(0, 5).map(id => ({ id })),
        },
        {
            name: "Infrastructure",
            weight: 2,
            monitorList: allMonitorIds.slice(5).map(id => ({ id })),
        },
    ];

    const saveStatusPageRes = await new Promise((resolve) => {
        socket.emit(
            "saveStatusPage",
            "platform",
            {
                slug: "platform",
                title: "Platform Status",
                description: "Real-time status of all platform services",
                theme: "auto",
                published: true,
                showTags: false,
                domainNameList: [],
                searchEngineIndex: false,
                showPoweredBy: true,
                googleAnalyticsId: "",
                showCertificateExpiry: false,
                customCSS: "",
                logo: "",
                footerText: "",
                rssTitle: "",
                showOnlyLastHeartbeat: false,
                analyticsId: null,
                analyticsScriptUrl: null,
                analyticsType: null,
                autoRefreshInterval: 300,
            },
            "", // imgDataUrl
            publicGroupList,
            resolve
        );
    });

    if (!saveStatusPageRes.ok) {
        throw new Error("Failed to save status page: " + saveStatusPageRes.msg);
    }
    console.log("Configured status page with monitors");

    // Add a tag
    const addTagRes = await new Promise((resolve) => {
        socket.emit("addTag", { name: "production", color: "#ff0000" }, resolve);
    });

    if (!addTagRes.ok) {
        throw new Error("Failed to add tag: " + addTagRes.msg);
    }
    console.log("Created tag: production");

    // Add a notification
    const addNotificationRes = await new Promise((resolve) => {
        socket.emit(
            "addNotification",
            {
                name: "Ops Email",
                type: "smtp",
                isDefault: false,
                applyExisting: false,
                smtpHost: "mail.example.com",
                smtpPort: 587,
                smtpSecure: false,
                smtpIgnoreTLSError: true,
                smtpDkimDomain: "",
                smtpDkimKeySelector: "",
                smtpDkimPrivateKey: "",
                smtpDkimHashAlgo: "sha256",
                smtpDkimheaderFieldNames: "",
                smtpDkimskipFields: "",
                smtpUsername: "ops@example.com",
                smtpPassword: "password123",
                customBody: null,
                to: "ops@example.com",
                cc: null,
                bcc: null,
                webhookContentType: null,
                kafkaProducerBrokers: null,
                kafkaProducerSaslOptions: null,
            },
            null,
            resolve
        );
    });

    if (!addNotificationRes.ok) {
        throw new Error("Failed to add notification: " + addNotificationRes.msg);
    }
    console.log("Created notification: Ops Email");

    console.log("\nSeed complete!");
    console.log("Created:", {
        monitors: Object.keys(monitorIds).length,
        paused: PAUSED_MONITOR_NAMES.length,
        statusPages: 1,
        tags: 1,
        notifications: 1,
    });

    socket.disconnect();
    process.exit(0);
}

seed().catch((err) => {
    console.error("Seed failed:", err.message);
    process.exit(1);
});
